kind: pipeline
name: Build & Deploy
type: docker

# services:
# - name: db
#   image: mysql
#   environment:
#     MYSQL_USER: root
#     MYSQL_PASSWORD: secret
#     MYSQL_ROOT_PASSWORD: secret
#     MYSQL_DATABASE: shop

steps:
# - name: Run Test
  # image: node:latest
  # depends_on:
  #   - db
  #   - redis
  # commands:
  #   - echo "start running test..."
  #   - bash ./build.sh

- name: publish  
  image: plugins/ecr
  settings:
    access_key: 
      from_secret: aws_access_key
    secret_key: 
      from_secret: aws_secret_key
    repo: 
      from_secret: aws_ecr_repo
    registry: 
      from_secret: aws_ecr_registry
    region:
      from_secret: aws_region
    tags:
        - 'test'

- name: slack
  image: plugins/slack
  # depends_on:
  #     # - Run Test
  #     - Deploy
  
  settings:
    webhook:
      from_secret: slack_webhook
    channel: go_shop
  when:
    status: [ success, failure ]

trigger:
  branch: 
    - main
  event: 
    - push